#pragma once
#include <stdio.h>
#include <math.h>
#include "allegro5/allegro.h"
#include <allegro5/allegro_image.h>
#include <allegro5/allegro_primitives.h>
#include "Enemy.h"
#include "Player.h"
#include "Render.h"
#include "Game.h"
